### ISSUE TITLE
Running discopy - discopy.version import

### ISSUE THREAD

**Issue by THIS-Usr** [discopy/discopy#270]
In init.py there is this code block extracted below.

```python

from discopy.version import (
    version as __version__,
    version_tuple as __version_info__)

```

I have run all the examples in examples.ipynb, but this is only possible if I comment out this code block.

I am uncertain where the error is?

**Comment by THIS-Usr** [comment]
I've resolved this.
I missed a step and didn't reason from correctly looking at the project locally (in PyCharm).
The discopy project I am working on takes precedence over any pip-installed version.
But it also needs to be installed with pip in order for the dynamically generated file, version.py, to be produced.

**Comment by toumix** [comment]
Thanks for documenting this issue! I've never used PyCharm so I wouldn't have known how to fix this, but it would be useful for future users who may get the same problem. Closing the issue since you've resolved it, but feel free to reopen if you need more support, I think @boldar99 knows PyCharm better.
