### ISSUE TITLE
Normalisation of mixed circuits

### ISSUE THREAD

**Issue by saskiabruhn** [discopy/discopy#96]
When I create a circuit, discard one of the wires and then compose it with its dagger and .eval(), I would expect it to be 1. The following code is a minimal example where the result of eval() deviates from 1.

```python
from discopy.quantum import Ket, Discard, Id, qubit
state = Ket(0, 0).Ry(0.1, 0).CRx(0.3, 0, 1) 
new_state = state >> Discard() @ Id(qubit)
(new_state >> new_state.dagger()).draw()
(new_state >> new_state.dagger()).eval(mixed=True)

**Comment by saskiabruhn** [comment]
Also happens if I post select instead of Discard:
```
state = Ket(0, 0).Ry(0.1, 0).CRx(0.3, 0, 1) 
new_state = state >> Bra(0) @ Id(qubit)
(new_state >> new_state.dagger()).draw()
(new_state >> new_state.dagger()).eval(mixed=True)

**Comment by y-richie-y** [comment]
I found an even simpler example:

```python
state = Ket(0, 0).H(0).CX(0, 1)
new_state = state >> Bra(0) @ Id(qubit)
(new_state >> new_state.dagger()).draw()
(new_state >> new_state.dagger()).eval(mixed=True)
# outputs: CQMap(dom=CQ(), cod=CQ(), array=[0.5+0.j])
```

<img width="617" alt="image" src="https://user-images.githubusercontent.com/13847804/198753882-4c559f13-b2fa-4660-aed5-a8b8beb59a6d.png">

If you look at this example, the state being prepared is a normalised bell state (`(|00> + |11>)/sqrt(2)` vs `|00> + |11>`), so the "inner product" is **quarter** of:

<img width="616" alt="image" src="https://user-images.githubusercontent.com/13847804/198754038-8172baab-bfcc-433b-8a7a-63fb2b4b9c1e.png">

Which evaluates to `CQMap(dom=CQ(), cod=CQ(), array=[2.+0.j])`.

(quarter because the normalised version has two `sqrt(2)` scalars, which when doubled during mixed eval becomes 4 `sqrt(2)`.)

**Comment by saskiabruhn** [comment]
When you do `MixedState().eval()` you get `CQMap(dom=CQ(), cod=Q(Dim(2)), array=[1.+0.j, 0.+0.j, 0.+0.j, 1.+0.j])`, which is unnormalised. Shouldn't the mixed state be normalised as it represents a density matrix which should have trace 1?

**Comment by toumix** [comment]
Originally we defined the mixed state as unnormalised because it was meant as the dagger of Discard. Maybe this is confusing and we should normalise it, then the dagger of Discard would be MixedState tensor a scalar.

Now for the core of the problem: you were expecting to get 1 by evaluating a normalised state followed by its dagger as a CQMap, but this is not the case in general. Indeed, if you read your diagram operationally, what happens it you are preparing a two-qubit mixed state then measuring the probability of it being in the Bell state. This is a quarter, but it gets scaled by the unnormalised mixed state as mentioned before.

The problem comes from a confusion between pure and mixed semantics. In the pure semantics, a state is normalised if composing it with its dagger gives 1. In the mixed semantics however, a state is normalised if its trace is 1, i.e. if composing it with Discard gives 1. See Chapter 8 in Coecke & Kissinger [Picturing Quantum](https://www.cambridge.org/core/books/picturing-quantum-processes/picturing-classicalquantum-processes/A571E05A571DE9196A75384266227E91).

![Screenshot 2022-11-02 at 11 04 36](https://user-images.githubusercontent.com/6673255/199461671-7dbbd7b1-a8bc-46a0-a5ba-b9ff49e341e6.png)

```python
Circuit.is_normalised = lambda self: (
    self >> Discard(self.cod)).eval().is_close(
        Discard(self.dom).eval())

state = Ket(0, 0).Ry(0.1, 0).CRx(0.3, 0, 1) 
new_state = state >> Discard() @ Id(qubit)

assert state.is_normalised() and new_state.is_normalised()
```

**Comment by saskiabruhn** [comment]
Thanks, that helps a lot!
